# Generated by Django 2.0.8 on 2018-09-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'patients',
            },
        ),
    ]
