# Generated by Django 2.0.8 on 2018-12-25 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('age', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('qualification', models.TextField(default='')),
                ('address', models.TextField(default='')),
                ('number', models.IntegerField(default=0)),
                ('fees', models.IntegerField(default=0)),
                ('gender', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(default='', max_length=6)),
                ('blood_group', models.CharField(default='', max_length=3)),
                ('weight', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('diabetes', models.BooleanField(default=False)),
                ('smoker', models.BooleanField(default=False)),
                ('drinker', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.Doctor')),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
