# Generated by Django 2.0.8 on 2019-04-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
