# Generated by Django 2.0.8 on 2019-02-19 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='patient',
            new_name='patient_id',
        ),
    ]
