# Generated by Django 2.0.8 on 2018-09-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_patients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
