# Generated by Django 2.0.8 on 2018-09-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_doctor_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='doctor_id',
            new_name='doctor',
        ),
    ]
